<?php
    $produits = array(
        array(
            "id" => 1,
            "name" => "Singe",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre singe adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "singe.jfif",
            "price" => 1000,
        ), array(
            "id" => 2,
            "name" => "Tigre",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre tigre adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "Tigre.jfif",
            "price" => 99.99,
        ), array(
            "id" => 3,
            "name" => "Zebre",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre zébre adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "zebre.jfif",
            "price" => 739.99,
        ), array(
            "id" => 4,
            "name" => "Cochon",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre cochon adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "cochon.jfif",
            "price" => 299.99,
        ), array(
            "id" => 5,
            "name" => "Chevre",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre chévre adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "chevre.jfif",
            "price" => 10000,
        ), array(
            "id" => 6,
            "name" => "Alpaga",
            "overview" => "Découvrez le compagnon le plus amusant et fascinant que vous ayez jamais rencontré : notre Alpaga adorable et intelligent !",
            "overview1" => "Adoptez cet animal exceptionnel et apportez une dose quotidienne de joie, d'aventure et d'amour dans votre vie.",
            "overview2" => "Ne manquez pas cette opportunité unique de vous offrir un ami pour la vie",
            "overview3" => "ACHETER",
            "image" => "alpaga.jfif",
            "price" => 3,
        ),
    );
?>